{
  "name": "test",
  "steps": [
    {
      "name": "build",
      "type": "BUILD",
      "service_account": "test-sa",
      "input": {
        "type": "git"
      },
      "outputs": [
        {
          "type": "image",
          "url": "zeromsi2/spring-boot-image:1.0.0",
          "revision": "1.0.0"
        }
      ],
      "arg": {
        "configMaps": [
          {
            "name": "cm-test",
            "namespace": "tekton"
          }
        ]
      }
    },
    {
      "name": "deploy",
      "type": "DEPLOY",
      "outputs": [
     {
          "deployment_resource": {
            "agent": "local_agent",
            "name": "ubuntu",
            "namespace": "default",
            "type": "deployment",
            "replica": 2,
            "images": [
              {
                "image_index": 0,
                "image": "zeromsi2/spring-boot-image:1.0.0"
              },
              {
                "image_index": 1,
                "image": "ubuntu"
              }
            ]
          }
        }
      ]
    }
  ]
}
