name: test
steps:
  - name: build
    type: BUILD
    trigger: AUTO
    params:
      repository_type: git
      service_account: test-sa
      images: zeromsi2/test-dev,zeromsi2/test-pro
      args_from_configmaps: tekton/cm-test
      args: key3:value1,key4:value2
    next: 
      - interstep
  - name: interstep
    type: INTERMEDIARY
    trigger: AUTO
    params:
      env: test
      revision: latest
      service_account: test-sa
      images: ubuntu
      envs_from_configmaps: tekton/cm-test
      envs_from_secrets: tekton/cm-test
      envs: key3:value1,key4:value2
      command: echo
      command_args: Hello World
      script: echo "Hello zeromsi"
    next:
      - deployDev
  - name: deployDev
    type: DEPLOY
    trigger: AUTO
    params:
      agent: localagent
      name: ubuntu
      namespace: default
      type: deployment
      revision: master
      trunk_based: enabled
      rollout_restart: true
      env: dev
      images: zeromsi2/test-dev
    next: 
      - jenkins
  - name: jenkins
    type: JENKINS_JOB
    trigger: AUTO
    params:
      env: edge
      url: http://jenkins.default.svc:8080
      job: new
      secret: jenkins-credentials
      params: id:123,verbosity:high   
    next: null
