name: test-pipelines
steps:
  - name: build
    type: BUILD
    trigger: AUTO
    params:
      repository_type: git
      revision: '121223234443434'
      service_account: test-sa
      images: zeromsi2/test-dev:1.0.0,zeromsi2/test-pro:1.0.0
      args_from_configmaps: tekton/cm-test
      arg: key3:value1,key4:value2
    next:
      - deployDev
  - name: deployDev
    type: DEPLOY
    trigger: AUTO
    params:
      agent: local_agent
      name: ubuntu
      namespace: default
      type: deployment
      env: dev
      images: zeromsi2/test-dev:1.0.0
    next: null
