name: test
steps:
  - name: build
    type: BUILD
    trigger: auto
    params:
      repository_type: git
      revision: '121223234443434'
      service_account: test-sa
      images: zeromsi2/test-dev:1.0.0,klovercloud/test:1.0.0
      args_from_configmaps: tekton/cm-test
      arg: key1:value1,key2:value2
    next:
      - deployDev
  - name: deployDev
    type: DEPLOY
    trigger: manual
    params:
      agent: local_agent
      name: ubuntu
      namespace: default
      type: deployment
      env: dev
      images: 0:ubuntu
    next: null
