name: test-pipeline
steps:
  - name: build
    type: BUILD
    trigger: AUTO
    params:
      repository_type: git
      revision: master
      service_account: test-sa
      images: zeromsi2/test-dev,zeromsi2/test-pro
      args_from_configmaps: tekton/cm-test
      args: key3:value1,key4:value2
    next: 
      - intermediray_step
  - name: intermediray_step
    type: INTERMEDIARY_STEP
    trigger: AUTO
    params:
      revision: master
      service_account: test-sa
      images: zeromsi2/test-dev,zeromsi2/test-pro
      envs_from_configmaps: tekton/cm-test
      envs_from_secrets: tekton/cm-test
      envs: key3:value1,key4:value2
    next:
      - deployDev
  - name: deployDev
    type: DEPLOY
    trigger: AUTO
    params:
      agent: local_agent
      name: ubuntu
      namespace: default
      type: deployment
      env: dev
      images: zeromsi2/test-dev
    next: null
