name: test
steps:
  - name: build
    type: BUILD
    trigger: AUTO
    params:
      repository_type: git
      revision: master
      service_account: test-sa
      images: zeromsi2/test-dev,zeromsi2/test-pro
      args_from_configmaps: tekton/cm-test
      arg: key3:value1,key4:value2
    next:
      - deployDev
  - name: deployDev
    type: DEPLOY
    trigger: AUTO
    params:
      agent: local_agent
      name: ubuntu
      namespace: default
      type: deployment
      env: dev
      images: zeromsi2/test-dev
    next: null
